### ISSUE TITLE
[Removal]

### ISSUE THREAD

**Issue by Canadaz** [Anomia-SBC/The-Holy-Sandbox-Blacklist#3]
#### Does your site run a source?
- [x] No

#### Are you the owner of the website?
- [x] Co-Owner / HR

### What is your website URL?
> [Website](https://brickorzo.com)

### What is your discord tag?
My discord tag is: Canada#2000

### Why should your website be removed?
> My site should be removed because it is not accurate. I do not understand the reasoning behind "Vulnerable" and me having bad management skills. How can a website be vulnerable if it has not been released to the public? Furthermore, I am very professional when it comes to Brickorzo. I made an entire server dedicated to our staff members, I give out moderation actions ONLY when they break rules. Meaning bans due to criticism, personal attacks, and trolling never occur. If you would like to get proof of the website being safe to use for the public, I would love to send you some code examples of Brickorzo to show that we do not have security vulnerabilities.

Please get back to me as soon as possible.

~ Canada

**Comment by Shigetorum635** [comment]
The site was added as part of the old brickorzo led by SuperJP.

I will now fix the tags even though entire removal will not be possible but will be kept in the "Unfinished" section. (Which will soon be easily distinguished from the actual blacklist)

Thanks for contacting.

**Comment by Shigetorum635** [comment]
Fixed.

**Comment by Canadaz** [comment]
Thank you for taking action.
