### ISSUE TITLE
Add site

### ISSUE THREAD

**Issue by stampe99** [Anomia-SBC/The-Holy-Sandbox-Blacklist#4]
http://blockcave.c1.biz/ owner unfinished

**Comment by Shigetorum635** [comment]
We will begin the review now.

**Comment by Shigetorum635** [comment]
### Review outcome.

- Domain name is free (c1.biz)
- Hosting platform is **outdated**
- traffic is **not encrypted** (HTTP)
- Website runs a source

Tags to be added:
`unfinished`, `owner`, `source`, `vulnerable`

Thank you for contacting.
