### ISSUE TITLE
[Removal]

### ISSUE THREAD

**Issue by queezyi** [Anomia-SBC/The-Holy-Sandbox-Blacklist#5]
#### Does your site run a source?
- [TRUE PUBLIC BACKEND PRIVATE FRONT END ALSO EDITED BACKEND ] Yes
- [ ] No
- [ ] Modified

#### Are you the owner of the website?
- [ ] Yes
- [TRUE ] Co-Owner / HR
- [ ] No

### What is your website URL?

> [Website](blox-city.net)

### What is your discord tag?

My discord tag is: Jp#0519

### Why should your website be removed?

> This site should not be removed but instead modified as the owner has changed from a scammer to a pretty cool guy also the source is not vulnerable as it has been modified to defend itself from attackers

**Comment by Shigetorum635** [comment]
> [TRUE PUBLIC BACKEND PRIVATE FRONT END ALSO EDITED BACKEND ] Yes

What does this mean

**Comment by Shigetorum635** [comment]
Anyhow, your site still does run a source. Which directly falls under the source category. For your site to be taken out from the blacklist one of our team members (@warlord-hash , @Kqpa  or @Shigetorum635 ) needs to check the source to verify such changes.

**Comment by Shigetorum635** [comment]
Closed for now.
