### ISSUE TITLE
[Site Add] 

### ISSUE THREAD

**Issue by stampe99** [Anomia-SBC/The-Holy-Sandbox-Blacklist#6]
Vetatorium - http://vetatorium.com/ & http://beta.vetatorium.com/ - Unfinished

**Comment by Shigetorum635** [comment]
in-review

**Comment by Shigetorum635** [comment]
Fixed in [6ec1455](https://github.com/Anomia-SBC/The-Holy-Sandbox-Blacklist/commit/6ec1455c102eb972fe24fccdcd65567eb9f6502e)
