### ISSUE TITLE
[Site Add] 

### ISSUE THREAD

**Issue by stampe99** [Anomia-SBC/The-Holy-Sandbox-Blacklist#7]
Buildaverse - buildaverse.com - unfinished

**Comment by Shigetorum635** [comment]
in-review

**Comment by Shigetorum635** [comment]
Fixed in [533d89f](https://github.com/Anomia-SBC/The-Holy-Sandbox-Blacklist/commit/533d89fed005f398cc14ef243c8eb65a62028e09)
